export enum DefinedPermissions {
  CreateSubmitPurchaseRequisition = 1,
  ApprovePurchaseRequisition = 2,
  CreateSubmitPurchaseOrder = 3,
  ApprovePurchaseOrder = 4,
  CanBuyGoods = 5,
  CanReceiveGoods = 6,
  ListOwnResources = 7,
  ListAssignedResources = 8,
  CreateBooking = 9,
  UpdateBooking = 10,
  ConfirmBooking = 11,
  LoadGoods = 12,
  OnlyTheSameSite = 24,
  OnlyPersonInCharge = 25,
}
